### ISSUE TITLE
New gc layout

### ISSUE THREAD

**Issue by lukeIam** [amshove/GC_little_helper#143]
- `#found# `, `#found_no#`, `#owner#` variables not filled
- `search field` causes a linebreak
- `Link bar on map` site is on the map and overlays the map-choose button
- `Default logtyp` not working
- Maybe move the `link bar` into the big green banner

**Comment by Confectrician** [comment]
Maybe move the logo up there too and replace it with a white version

**Comment by lukeIam** [comment]
Template fix + changed user name crawling:
https://github.com/lukeIam/GC_little_helper/blob/newLayout/gc_little_helper.user.js

**Comment by lukeIam** [comment]
- Added option for custom header layout (not on the map page yet)
-Fix searchfield position

https://github.com/lukeIam/GC_little_helper/blob/newLayout/gc_little_helper.user.js

**Comment by lukeIam** [comment]
Layout changed - All problem should be fixed here:
https://github.com/lukeIam/GC_little_helper/blob/newLayout/gc_little_helper.user.js

**Comment by PontiacCZ** [comment]
The linked page nearly freezes my browser (either FF  or IE) - how to get the code from there?

**Comment by PontiacCZ** [comment]
Oh - OK, the RAW button is the way to go. So I managed to copy the code and put it over the old one in my FF, then saved - but cache pages are still broken, the navigation column that used to be on the right is under the page. 
You likely linked the old code. It still shows 11.4 version, so it is the old version.

**Comment by RichardVisage** [comment]
Almost there guys!  In FF 37.0.1, the mouse-over link for your profile in the top menu bar are slightly off alignment.   If I mouse-over my total cache finds, it is click-able, but move up slightly to hover over my caching name, and the link is gone.  It either needs to be bumped up a bit, or enlarged to encompass both the caching name and find count, and perhaps even the profile image as well.

Great work, thanks for keeping GC Little Helper going!

**Comment by lukeIam** [comment]
> the mouse-over link for your profile in the top menu bar are slightly off alignment. If I mouse-over my total cache finds, it is click-able, but move up slightly to hover over my caching name, and the link is gone.

confirmed - but I do not know the reason...
everything is warped in <a> tag but the click able region is smaller...

**Comment by lukeIam** [comment]
Sould be fixed in the current release
